sequenceDiagram
    participant Driver
    participant lib_frontend
    participant lib_ir
    participant lib_callgraph
    autonumber
    Activate Driver
    Driver->>+lib_frontend: astFromFiles(files)
    loop for file in files
        Activate lib_frontend
        lib_frontend->>lib_frontend: buildProgram(file)
        Deactivate lib_frontend
    end
    Activate lib_frontend
    lib_frontend->>lib_frontend: preProcess(ast)
    Deactivate lib_frontend
    lib_frontend-->>-Driver: ast
    Driver->>+lib_frontend: addBindings(ast)
    lib_frontend->>+lib_ir: new SymbolTable()
    lib_ir-->>-lib_frontend: symbolTable
    lib_frontend-->>-Driver: ast
    Deactivate Driver